bootstrapBrokers: "my-cluster-kafka-bootstrap:9092"
# Container port
port: 8000
pollIntervalSeconds: 5
clientGroupId: "kafkalagexporter"
logLevel: INFO
kafkaLogLevel: INFO
image:
  repository: lightbend/kafka-lag-exporter
  tag: 0.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
